name: Sugerencia de Mejora
description: Sugerir una mejora o feature para el proyecto
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## Pre-requisitos"
  - type: markdown
    attributes:
      value: |
        Antes de sugerir una feature, busca [features existentes](https://github.com/jpxoi/pastoral-digital-app/issues)
  - type: textarea
    attributes:
      label: Descripción
      description: Descripción de la feature que quieres que se añada
      placeholder: |
        Estaría bien que el proyecto tuviese ...
    validations:
      required: true